### ISSUE TITLE
Unloading Harvester Brake and Go

### ISSUE THREAD

**Issue by sootysax** [DeckerMMIV/FarmSim_Mod_FollowMe#14]
Running my harvester at 6MPH, and have a tractor with tipper following at 5.5 offset and +9 in front offset.

Instead of just cruising next to the combine and unloading, he drives up to the offset, hits the brakes and falls behind...  cruises up to the offset, hits the brakes and falls behind

update:  this seems to be a battle of control between Drive Control and Follow Me.  If Drive Control is removed from the mods, this behavior stops - it will slam on the brakes the first time it approaches the combine, but seems to cruise along better afterwards.   I feel like DC introduces something that causes the acceleration to be sluggish from a dead stop..   either way, it feels like the brakes are getting hit too hard when it hits the offset point

**Comment by DeckerMMIV** [comment]
The "hit the brakes"-problem was also occurring in the FS2013/FS15 versions of Follow Me.

It happens when the follower comes 'ahead' of a 'crumb' - essentially "it has driven too far".

In the development version I'm trying to test now, it should occur less, as I've changed some of the speed algorithm - but it will not truly go away.

**Comment by DeckerMMIV** [comment]
Please download the version 1.1.0.35, and see if it fixes the problem.

**Comment by DeckerMMIV** [comment]
Closing this issue, due to it being very old.
